name: metrics

on:
  schedule: [{ cron: "0 0 * * 0" }] # At 00:00 oevery Sunday
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: jhdcruz
          template: classic
          base: repositories
          config_timezone: Asia/Manila
          repositories_affiliations: owner, collaborator
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
          plugin_lines: yes
          plugin_lines_sections: history, repositories
          plugin_lines_repositories_limit: 4
          plugin_lines_history_limit: 1
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_threshold: 1%
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_wakatime_sections: "language-graphs, os-graphs, time"
