name: GH Metrics

on:
  schedule: [{ cron: "0 0 * * 0" }] # At 00:00 every Sunday
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: jhdcruz
          template: classic
          base: metadata
          config_timezone: Asia/Manila
          repositories_affiliations: owner, collaborator
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_threshold: 1%
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_limit: 7
